service: hello-slack-apps
frameworkVersion: '2 || 3'

provider:
  name: aws
  stage: dev
  runtime: python3.8
  region: eu-west-1
  logRetentionInDays: 5
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: lambda_handler.handler
    memorySize: 128
    events:
      - httpApi:
          path: /say
          method: post
